# Generated by Django 5.2.4 on 2025-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('format', models.CharField(default='text', max_length=300)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
