# Generated by Django 5.2.4 on 2025-07-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askly', '0002_prompttemplate_alter_questionanswer_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='context',
            new_name='prompt',
        ),
    ]
